### ISSUE TITLE
Allow fetching from a Git URL

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/ruby-paneron_registry#1]
... rather than from just a local file system path.

**Comment by ronaldtse** [comment]
@ribose-jeffreylau is this completed?

**Comment by ribose-jeffreylau** [comment]
Requirements:

- fetching from a GitHub URL
- no specific location for local git cache (for macOS, probably somewhere in "$HOME/Application Support"?)

As such, the following Git gems can be considered:

- https://github.com/octokit/octokit.rb
- https://github.com/ruby-git/ruby-git

**Comment by ribose-jeffreylau** [comment]
Done in 9002270f4bdc014f838862520b6e35cf17f58175
