### ISSUE TITLE
Allow write access

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/ruby-paneron_registry#3]
Potentially depends on #1

**Comment by ronaldtse** [comment]
@ribose-jeffreylau can we rename this gem to paneron-register? We don’t use the word “registry” anymore in ISO 19135, and the hyphen works better than then underscore. Thanks!

**Comment by ribose-jeffreylau** [comment]
@ronaldtse Sure, please see #4

**Comment by ronaldtse** [comment]
@ribose-jeffreylau one more thing. Could you use lutaml-model to read/model the Paneron files? Thanks!

**Comment by ribose-jeffreylau** [comment]
Fixed by 1cabf63ffcfc7b8ca1d5c5f390a37195e4d203c3
