### ISSUE TITLE
Rename Registry -> Register

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/ruby-paneron_registry#4]
According to https://guides.rubygems.org/name-your-gem/, we have the following options and implications:

- gem name: `paneron-register`
  require statement: `require "paneron/register"`
  module/class name: `Paneron::Register`
- gem name: `paneron_register`
   require statement: `require "paneron_register"`
   module/class name: `PaneronRegister`

**Comment by ribose-jeffreylau** [comment]
We'll use the one with hyphen (see https://github.com/paneron/ruby-paneron_registry/issues/3#issuecomment-2419240576)

**Comment by ronaldtse** [comment]
Thanks! Yes the namespaced option seems appropriate for this case.
