### ISSUE TITLE
Provide an integrated example on how to actually use the gem 

### ISSUE THREAD

**Issue by ronaldtse** [paneron/ruby-paneron_registry#6]
@ribose-jeffreylau please provide a full integrated an example to:
* Show how to create a register
* How to register an item class
* How to store a file in the item
* How to write the item to register (sync local to remote)
* How to fetch the item for use
* How to obtain the file from the item

Thanks

**Comment by ribose-jeffreylau** [comment]
Completion of this will depend on the following:

- [x] #7 
- [x] #10 
- [x] #8 
- [x] #3

**Comment by ribose-jeffreylau** [comment]
Fixed by bd9aef5393197c89bf3f3d5abca9fa36c142f428 and f9a5d29e367797baaa3f57ae5fb07aad8bd92523.
